//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Boxcars.Engine")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+1e23df9bc3eefda9f5f10d6b0f2d6be70299284b")]
[assembly: System.Reflection.AssemblyProductAttribute("Boxcars.Engine")]
[assembly: System.Reflection.AssemblyTitleAttribute("Boxcars.Engine")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Boxcars.Engine.Tests")]

// Generated by the MSBuild WriteCodeFragment class.

